# Generated by Django 3.0.2 on 2020-02-08 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='boardmodel',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
